### PR TITLE
fix: pass headers when connecting sockets

### LINKED ISSUE #1359: Security: allowed origins should not be * by default
CORS headers should be restricted to the current domain at least, by default.

### PR DESCRIPTION
**Pull request by willydouhard**
Fixing https://github.com/Chainlit/chainlit/issues/1279 and closes #1359 as well. Tested it on GCP with session affinity + 2 instances with this docker file

```dockerfile
# Build stage for Python application
FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

# Install pnpm
RUN npm install -g pnpm

# Set working directory
WORKDIR /app

# Copy your application files
COPY app.py .

# Install Python dependencies
RUN pip install --no-cache-dir git+https://github.com/Chainlit/chainlit.git@willy/sticky-sessions#subdirectory=backend/

# Set environment variables
ENV PORT=8000
ENV HOST=0.0.0.0

# Expose the port
EXPOSE 8000

# Start the application
CMD ["chainlit", "run", "app.py", "--host", "0.0.0.0", "--port", "8000", "-h"]
```

### CODE REVIEW

**Comment by willydouhard** [comment]
This is failing for any origin that is the not the server's origin (typically Chainlit embedded as a copilot on a website) because `withCredential` does not support `'*'` cross origin.

```
Access to XMLHttpRequest at 'https://chainlit-sticky-182925357376.europe-west2.run.app/ws/socket.io/?EIO=4&transport=polling&t=PEh9E88' from origin 'http://localhost:9000/' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

**Comment by willydouhard** [comment]
The issue is fixed. For cross origin use cases, it is now mandatory to allow it in the project config (I had to update the [copilot test](https://github.com/Chainlit/chainlit/pull/1575/files#diff-251fceb4f6dd0cf218e8f0579b2f5810ea1e4723de4268080482226f6c8c1f98R16) for example) as the wildcard `"*"` is not supported with credentials.

File: libs/react-client/src/useChatSession.ts [hunk 1]
```diff
@@ -100,6 +100,8 @@ const useChatSession = () => {
 
       const socket = io(uri, {
         path,
+        withCredentials: true,
+        transports: ['websocket'],
```
Comment (evantahler) [inline libs/react-client/src/useChatSession.ts:104]: This change works for our use-case, but I believe adding the `transports` option here means that Socket.IO will not fall back to long-polling if a WS connection can't be established.  There are probably still some load balancers/browsers out there that can't handle web-sockets properly.  It might be helpful for these options to become chainlit initialization options that the user can select?

File: backend/chainlit/config.py [hunk 2]
```diff
@@ -311,6 +311,8 @@ class CodeSettings:
 @dataclass()
 class ProjectSettings(DataClassJsonMixin):
     allow_origins: List[str] = Field(default_factory=lambda: ["*"])
+    # Socket.io client transports option
+    transports: Optional[List[str]] = None
```
Comment (willydouhard) [inline backend/chainlit/config.py:315]: made the transports configurable @evantahler

**Comment by willydouhard** [comment]
Here is the doc PR https://github.com/Chainlit/docs/pull/199

**Comment by evantahler** [comment]
I gave this branch a try within our application, but every request I made is rejected:
* Clint WS message: `{"message":"Connection rejected by server"}`
* Server: `{"type":"LOG","log":{"level":"INFO","message":"Authentication failed"}}`

We have a custom data layer, but I tried removing it with the same (failing) results. Any tips?

**Comment by evantahler** [comment]
Note: Poetry install line for `pyproject.toml`

```
chainlit = { git = "ssh://git@github.com/chainlit/chainlit.git", branch = "willy/sticky-sessions", subdirectory = "backend" }
```

**Comment by dokterbob** [comment]
> Note: Poetry install line for `pyproject.toml`
> 
> ```
> chainlit = { git = "ssh://git@github.com/chainlit/chainlit.git", branch = "willy/sticky-sessions", subdirectory = "backend" }
> ```

Convenient one-liner - not requiring authentication/write access to the repo:
```sh
poetry add git+https://github.com/Chainlit/chainlit.git@willy/sticky-sessions#subdirectory=backend/
```

**Comment by dokterbob** [comment]
> I gave this branch a try within our application, but every request I made is rejected:
> 
> * Clint WS message: `{"message":"Connection rejected by server"}`
> * Server: `{"type":"LOG","log":{"level":"INFO","message":"Authentication failed"}}`
> 
> We have a custom data layer, but I tried removing it with the same (failing) results. Any tips?

Could you share a screendump of the browser's console and network requests from the debugger? Particularly the websocket initialisation process. Details on the first non-successful request from the network debugger would also help.

**Comment by dokterbob** [comment]
@dvdr00t  This probably also solves #1407. Any chance you could give it a try? More eyes on this the better. :)

**Comment by evantahler** [comment]
Sure!  We are using a FastAPI application & `mount_chainlit`

Server Logs:
```
10:00:54 api.1       | INFO:     127.0.0.1:57431 - "GET /api/v1/users/me HTTP/1.1" 200 OK
10:00:54 api.1       | INFO:     127.0.0.1:57431 - "GET /chat/auth/config HTTP/1.1" 200 OK
10:00:54 api.1       | {"type":"LOG","log":{"level":"WARN","message":"Translated markdown file for en-US not found. Defaulting to chainlit.md."}}
10:00:54 api.1       | INFO:     127.0.0.1:57431 - "GET /chat/auth/config HTTP/1.1" 200 OK
10:00:54 api.1       | INFO:     127.0.0.1:57434 - "GET /chat/project/settings?language=en-US HTTP/1.1" 200 OK
10:00:54 api.1       | INFO:     127.0.0.1:57434 - "GET /api/v1/chat/auth HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     127.0.0.1:57434 - "GET /api/v1/chat/auth HTTP/1.1" 200 OK
10:00:55 api.1       | {"type":"LOG","log":{"level":"WARN","message":"Translated markdown file for en-US not found. Defaulting to chainlit.md."}}
10:00:55 api.1       | INFO:     127.0.0.1:57434 - "GET /chat/auth/config HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     127.0.0.1:57431 - "GET /chat/project/settings?language=en-US HTTP/1.1" 200 OK
10:00:55 api.1       | {"type":"LOG","log":{"level":"WARN","message":"Translated markdown file for en-US not found. Defaulting to chainlit.md."}}
10:00:55 api.1       | INFO:     127.0.0.1:57434 - "GET /chat/auth/config HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     127.0.0.1:57431 - "GET /chat/project/settings?language=en-US HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     127.0.0.1:57434 - "POST /chat/project/threads HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     127.0.0.1:57431 - "POST /chat/project/threads HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     127.0.0.1:57431 - "OPTIONS /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6pmpfx HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     127.0.0.1:57434 - "GET /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6pmpfx HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     127.0.0.1:57434 - "OPTIONS /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6qz0a3&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     ('127.0.0.1', 57441) - "WebSocket /chat/ws/socket.io/?EIO=4&transport=websocket&sid=ochdon-Bc-f-hV5YAAAA" [accepted]
10:00:55 api.1       | INFO:     127.0.0.1:57431 - "OPTIONS /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6r0pdd&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     connection open
10:00:55 api.1       | {"type":"LOG","log":{"level":"INFO","message":"Authentication failed"}}
10:00:55 api.1       | INFO:     127.0.0.1:57443 - "POST /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6qz0a3&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     127.0.0.1:57434 - "GET /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6r0pdd&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     127.0.0.1:57434 - "OPTIONS /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6td00j&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     127.0.0.1:57443 - "GET /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6td00j&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     127.0.0.1:57443 - "OPTIONS /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6v2btm&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     127.0.0.1:57434 - "GET /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6v2btm&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
10:00:55 api.1       | INFO:     connection closed
```

Some screenshots from the browser console:

Screenshot 2024-12-10 at 9 59 58 AM
Screenshot 2024-12-10 at 9 59 32 AM

**Comment by dokterbob** [comment]
Incidentally, a prior PR for this issue was already open #1339. Should close it once we merge this.

**Comment by dokterbob** [comment]
> Sure! We are using a FastAPI application & `mount_chainlit`
> 
> Server Logs:
> 
> ```
> 10:00:54 api.1       | INFO:     127.0.0.1:57431 - "GET /api/v1/users/me HTTP/1.1" 200 OK
> 10:00:54 api.1       | INFO:     127.0.0.1:57431 - "GET /chat/auth/config HTTP/1.1" 200 OK
> 10:00:54 api.1       | {"type":"LOG","log":{"level":"WARN","message":"Translated markdown file for en-US not found. Defaulting to chainlit.md."}}
> 10:00:54 api.1       | INFO:     127.0.0.1:57431 - "GET /chat/auth/config HTTP/1.1" 200 OK
> 10:00:54 api.1       | INFO:     127.0.0.1:57434 - "GET /chat/project/settings?language=en-US HTTP/1.1" 200 OK
> 10:00:54 api.1       | INFO:     127.0.0.1:57434 - "GET /api/v1/chat/auth HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     127.0.0.1:57434 - "GET /api/v1/chat/auth HTTP/1.1" 200 OK
> 10:00:55 api.1       | {"type":"LOG","log":{"level":"WARN","message":"Translated markdown file for en-US not found. Defaulting to chainlit.md."}}
> 10:00:55 api.1       | INFO:     127.0.0.1:57434 - "GET /chat/auth/config HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     127.0.0.1:57431 - "GET /chat/project/settings?language=en-US HTTP/1.1" 200 OK
> 10:00:55 api.1       | {"type":"LOG","log":{"level":"WARN","message":"Translated markdown file for en-US not found. Defaulting to chainlit.md."}}
> 10:00:55 api.1       | INFO:     127.0.0.1:57434 - "GET /chat/auth/config HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     127.0.0.1:57431 - "GET /chat/project/settings?language=en-US HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     127.0.0.1:57434 - "POST /chat/project/threads HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     127.0.0.1:57431 - "POST /chat/project/threads HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     127.0.0.1:57431 - "OPTIONS /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6pmpfx HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     127.0.0.1:57434 - "GET /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6pmpfx HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     127.0.0.1:57434 - "OPTIONS /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6qz0a3&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     ('127.0.0.1', 57441) - "WebSocket /chat/ws/socket.io/?EIO=4&transport=websocket&sid=ochdon-Bc-f-hV5YAAAA" [accepted]
> 10:00:55 api.1       | INFO:     127.0.0.1:57431 - "OPTIONS /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6r0pdd&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     connection open
> 10:00:55 api.1       | {"type":"LOG","log":{"level":"INFO","message":"Authentication failed"}}
> 10:00:55 api.1       | INFO:     127.0.0.1:57443 - "POST /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6qz0a3&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     127.0.0.1:57434 - "GET /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6r0pdd&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     127.0.0.1:57434 - "OPTIONS /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6td00j&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     127.0.0.1:57443 - "GET /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6td00j&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     127.0.0.1:57443 - "OPTIONS /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6v2btm&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     127.0.0.1:57434 - "GET /chat/ws/socket.io/?EIO=4&transport=polling&t=rp6v2btm&sid=ochdon-Bc-f-hV5YAAAA HTTP/1.1" 200 OK
> 10:00:55 api.1       | INFO:     connection closed
> ```
> 
> Some screenshots from the browser console:
> 
> Screenshot 2024-12-10 at 9 59 58 AM Screenshot 2024-12-10 at 9 59 32 AM

Thanks. That was quick! Could you send the browser's Console as well?

I am about to test with a similar setup for our own application RN.

**Comment by dokterbob** [comment]
@evantahler The auth error comes from here: https://github.com/Chainlit/chainlit/blob/8b2d4bacfd4fa2c8af72e2d140d527d20125b07b/backend/chainlit/socket.py#L117

Could you remove the try/except there, or change it into `console.exception()` to get the underlying Exception?

**Comment by dokterbob** [comment]
On my setup (no custom data layer, but using `mount_chainlit()`, with a single instance, I don't get authorization errors.

**Comment by evantahler** [comment]
The browser console for this page is just tons of react errors about tooltips and mimetypes.  Here's the output in a gist - https://gist.github.com/evantahler/171f6aa0a9f862c0122ec0728d8c430c

**Comment by dokterbob** [comment]
GTG now, happy to look again tomorrow. Any discriminating factors (what auth are you using) and/or feedback from other users greatly appreciated.

**Comment by evantahler** [comment]
> @evantahler The auth error comes from here:
> 
> https://github.com/Chainlit/chainlit/blob/8b2d4bacfd4fa2c8af72e2d140d527d20125b07b/backend/chainlit/socket.py#L117
> 
> Could you remove the try/except there, or change it into `logger.exception()` to get the underlying Exception?

Looks like my `auth` is none:

``
10:45:00 api.1       | {"type":"LOG","log":{"level":"ERROR","message":"Authentication failed\nTraceback (most recent call last):\n  File \"/Users/evan/Library/Caches/pypoetry/virtualenvs/app---U6Ca7R-py3.10/lib/python3.10/site-packages/socketio/async_server.py\", line 555, in _handle_connect\n    success = await self._trigger_event(\n  File \"/Users/evan/Library/Caches/pypoetry/virtualenvs/app---U6Ca7R-py3.10/lib/python3.10/site-packages/socketio/async_server.py\", line 637, in _trigger_event\n    ret = await handler(*args)\nTypeError: connect() missing 1 required positional argument: 'auth'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/evan/Library/Caches/pypoetry/virtualenvs/app---U6Ca7R-py3.10/lib/python3.10/site-packages/chainlit/socket.py\", line 97, in connect\n    token = auth.get(\"token\")\nAttributeError: 'NoneType' object has no attribute 'get'"}}
```

**Comment by evantahler** [comment]
Perhaps I'm still using an older version of the UI... any way to confirm that it has been re-compiled/re-built?

**Comment by dokterbob** [comment]
> Perhaps I'm still using an older version of the UI... any way to confirm that it has been re-compiled/re-built?
> 
> Edit: Screenshot 2024-12-10 at 11 01 15 AM
> 
> I /think/ that the fact that the websocket request is not including any cookie header matches this

Yes, that seems most likely. Can you share your Dockerfile? 

Normally, `poetry install` should trigger `npm buildUi`, which builds the UI - then it copies it to chainlit/backend/chainlit/frontend/dist` from where chainlit serves it.

However, if you are running a chainlit install from the repo (as should be the case for source builds), AFAIK it serves from `frontend/dist` instead.

The obvious way is to add a `console.log()` somewhere. ;)

**Comment by willydouhard** [comment]
Most likely using an old version of the UI. The auth change happens in the react-client (which is supposed to be rebuilt as well by `pnpm run buildUi`).

**Review by dokterbob — APPROVED** [review]
I've just done repeated login/logout testing with 4 instances on GCP with OAuth. Used private browser and normal browser. No problems whatsoever. I think we should merge this and have users test it in a release candidate.!

**Comment by evantahler** [comment]
>  I think we should merge this and have users test it in a release candidate!

Excellent! Can you comment here when that RC is ready to try out?

**Comment by asvishnyakov** [comment]
@willydouhard @dokterbob Just installed chainlit from main branch and got the same message about `TypeError: connect() missing 1 required positional argument: 'auth'\n\n`

**Comment by willydouhard** [comment]
I am not able to reproduce, did you rebuild the entire UI including the react client? The auth change is actually in the react client which is a dependency of the main frontend.

**Comment by willydouhard** [comment]
The pre-release is available @evantahler @asvishnyakov.

```
pip3 install -U --pre chainlit
```

Let me know if it works on your end.

**Comment by asvishnyakov** [comment]
@willydouhard Thank you! [This](frontend/src/components/organisms/sidebar/index.tsx) resolved the issue. Glad to be able use new version, it has amazing features!

**Comment by evantahler** [comment]
We are using a custom frontend (`@chainlit/react-client`), and it looks like a new version of the frontend hasn't been pushed to NPM yet https://www.npmjs.com/package/@chainlit/react-client?activeTab=versions

**Comment by willydouhard** [comment]
I just released it, version `0.2.1`.

> We are using a custom frontend (`@chainlit/react-client`), and it looks like a new version of the frontend hasn't been pushed to NPM yet https://www.npmjs.com/package/@chainlit/react-client?activeTab=versions

**Comment by munday-tech** [comment]
@willydouhard I really think the removal of extra headers should be marked as a potentially breaking change. If anyone is relying on these headers downstream, for load balancing etc this has the potential to entirely break the use of the app for them.
